name: info_breakingbad
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
 # State managemant
  flutter_riverpod: ^1.0.0
 # Apis
  dio: ^4.0.4
 # UI
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter_offline: ^2.0.0
  flutter:
    sdk: flutter
  
  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
